language: r

env:
  global:
    - secure: "LrtJ9FCVVqbJPDvgME/Ub3UitJMxhxqUxPgUK310QbOHMuclbXzgRhCC1QZ6J2oXPHj/jMZJfBktlCcaUNnAsK4TudL0aze7lGu2dtohXmw8Jxt2OM32VYlzHtrFz+rYB2Pdy9QKrrBejj+AUoQpmGelkli4iWadAeutaZv/+M9HFLCfy2ieVW9Qv8SnMokEgktYB72JeosfIEi84VOI6RaVB4y96hhLettF9kcCvNPUWRdz+NKsqcISveIejHQuwuqaOKXu51biMsW6r7v2VZgMU34TRMvjPQnvomQsMzYT4LX73mN4ZEiziJArrxg2k4/DDxW7vLMaS3FBJbmEiap/FRi+DkcpEE5jvA2rSqYXt98oyin6HupEj1WVGvdi8cA5PwnoDzbopahbF/KacrOt3UfNU6GAgu0m0AlXXLYv78uL1cgks8Be1rUVnCdbVw72/ONLyI9EPDyaKEXGSXXmacCEBbc/jONEQzz9t9cM8tXxPRSIljklSN+1D645VQgZRyEXFlCB1tYPatmfiiZPvPbwViLJWXrt+orNJoxdIOqts6qFeWa74gv9zRJfso3O9E0gBv5JJh6YOTq5n2+bRynBqRUpb0R4x5zD00+xJ27/8/NdsrGXhsTRwt+SMxHxhNJ0mAaez6AnydQZnNGRkveKLMQxodB5+JrIgl0="
    
before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh