---
title: "Course Notes | Text Mining with R | DataCamp"
author: ""
date: "`r Sys.Date()`"
description: "This is my note"
output:
  prettydoc::html_pretty:
    theme: Cayman
    highlight: github
---

```{r, include=FALSE}
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("tidytext")) install.packages("tidytext")
if (!require("wordcloud")) install.packages("wordcloud")
```


# Courses: [Text Mining with R | Data Camp](https://www.datacamp.com/tracks/text-mining-with-r?version=2)

Different approaches to organizing and analyzing data of the text variety (books, articles, documents). A primer into regular expressions and ways to effectively search for common patterns in text is also provided

## Introduction to Text Analysis in R

Analyze text data in R using the tidy framework.

- [Wrangling Text](https://chinhungtseng.github.io/datacamp_text_mining_with_r/01.html)
- [Visualizing Text](https://chinhungtseng.github.io/datacamp_text_mining_with_r/02.html)
- [Sentiment Analysis](https://chinhungtseng.github.io/datacamp_text_mining_with_r/03.html)
- [Topic Modeling](https://chinhungtseng.github.io/datacamp_text_mining_with_r/04.html)

## String Manipulation in R with stringr

Learn how to pull character strings apart, put them back together and use the stringr package.

- [String basics](https://chinhungtseng.github.io/datacamp_text_mining_with_r/05.html)
- [Introduction to stringr](https://chinhungtseng.github.io/datacamp_text_mining_with_r/06.html)
- [Pattern matching with regular expressions](https://chinhungtseng.github.io/datacamp_text_mining_with_r/07.html)
- [More advanced matching and manipulation](https://chinhungtseng.github.io/datacamp_text_mining_with_r/08.html)
- [Case studies](https://chinhungtseng.github.io/datacamp_text_mining_with_r/09.html)

## Text Mining: Bag of Words

Learn the bag of words technique for text mining with R.

- [Jumping into text mining with bag of words](https://chinhungtseng.github.io/datacamp_text_mining_with_r/10.html)
- [Word clouds and more interesting visuals](https://chinhungtseng.github.io/datacamp_text_mining_with_r/11.html)
- [Adding to your tm skills](https://chinhungtseng.github.io/datacamp_text_mining_with_r/12.html)
- [Battle of the tech giants for talent](https://chinhungtseng.github.io/datacamp_text_mining_with_r/13.html)


## Sentiment Analysis in R

Learn sentiment analysis by identifying positive and negative language, specific emotional intent and making compili...

- [Fast & dirty: Polarity scoring](https://chinhungtseng.github.io/datacamp_text_mining_with_r/14.html)
- [Sentiment analysis the tidytext way](https://chinhungtseng.github.io/datacamp_text_mining_with_r/15.html)
- [Visualizing sentiment](https://chinhungtseng.github.io/datacamp_text_mining_with_r/16.html)
- [Case study: Airbnb reviews](https://chinhungtseng.github.io/datacamp_text_mining_with_r/17.html)
