library(remotes)

#install_version("tidyverse", "1.1.1")
install_version("nycflights13", "0.2.1")
install_version("okcupiddata", "0.1.0")
install_version("fivethirtyeight", "0.4.0")
install_version("babynames", "0.2.1")
#install_version("mosaic", "0.14.4")
install_version("gapminder", "0.3.0")
install_version("knitr", "1.15.1")
#install_version("broom", "0.4.2")
